---
name: Build and Test

on:
  push:
    branches-ignore:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: npm i conventional-changelog-conventionalcommits

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.10.0
      with:
        config-file-path: ./.changelog.config.js
        skip-version-file: true
        skip-commit: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: zulu
        java-version: 8.0.312+7

    - name: Deploy to GitHub
      run: mvn --no-transfer-progress -Psecuritycheck -Djgitver.use-version=${{ steps.changelog.outputs.version }} -DuseGitHubPackages=true clean verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/*.jar,LICENSE.txt,target/CHANGELOG.md"
        tag: ${{ steps.changelog.outputs.tag }}
        name: Release ${{ steps.changelog.outputs.version }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
        token: ${{ secrets.GITHUB_TOKEN }}
