name: Deploy to prod

on:
  push:
    tags:
      - 'production'

jobs:
  build:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

