name: "CI/CD gitflow: merged PR followup"

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: cleanup
        uses: jessfraz/branch-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
