name: "CI/CD gitflow: push feature branch"
on:
  push:
    branches: [ feature/* ]

jobs:
  verify-feature-build:
    name: Build Feature Branch
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        output_file: m2_settings.xml
        repositories: '[{ "id": "github-packages", "url": "https://maven.pkg.github.com/sabio-engineering/*" }]'
        servers: '[{
            "id": "github-packages",
            "username": "read-only-access",
            "password": "${{ secrets.NEXUS_PASSWORD }}"
          }, {
            "id": "fubar",
            "username": "${{ secrets.NEXUS_USERNAME }}",
            "password": "${{ secrets.NEXUS_PASSWORD }}"
          }]'

      # with:
      #   output_file: m2_settings.xml
      #   servers: '[{"id":"dev-nexus-abvprp","username":"${{ secrets.NEXUS_USERNAME }}","password":"${{ secrets.NEXUS_PASSWORD }}"},{"id":"github-packages","username":"${{ secrets.GH_USER }}","password":"${{ secrets.GH_PASSWORD }}"},{"id":"github","username":"${{ github.actor }}","password":"${{ secrets.GITHUB_TOKEN }}"}]'
        # repositories: >
        #   [
        #     {
        #       "id": "github-packages",
        #       "url": "https://maven.pkg.github.com/aboveproperty/*"
        #     }
        #   ]
        # mirrors: >
        #   [
        #     {
        #       "id": "dev-nexus-abvprp",
        #       "name": "Above Property Nexus",
        #       "mirrorOf": "external:*,!github-packages",
        #       "url": "https://nexus.dev.abvprp.com/repository/Public-Repositories/"
        #     }
        #   ]
        # profiles: >
        #   [
        #     {
        #       "id": "AboveProperty-Profile",
        #       "name": "foo.profile",
        #       "url": "http://foo.bar.profile",
        #       "properties": {
        #         "foo": "property-1",
        #         "bar": "property-2"
        #       }
        #     }
        #   ]
        # active_profiles: >
        #   [
        #     "AboveProperty-Profile"
        #   ]

    - run: cat m2_settings.xml

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up JDK 1.8
      id: checkout
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: zulu
        java-version: 8.0.312+7

    - name: Set up nexus
      uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: >
          [
            {
                "id": "dev-nexus-abvprp",
                "username": "${{ secrets.nexus_username }}",
                "password": "${{ secrets.nexus_password }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "dev-nexus-abvprp",
              "name": "Above Property Nexus",
              "mirrorOf": "external:*",
              "url": "https://nexus.dev.abvprp.com/repository/Public-Repositories/"
            }
          ]

    - run: cat $HOME/.m2/settings.xml

    - name: Install Commitlint Dependencies
      id: dependencies
      run: npm install @commitlint/config-conventional

    - name: Lint commit messages
      id: commitlint
      uses: wagoid/commitlint-github-action@v4
      with:
        configFile: .commitlint.config.js

    - name: maven verify
      id: verify
      run: mvn --no-transfer-progress clean verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

