name: "CI/CD gitflow: push feature branch"
on:
  push:
    branches: [ feature/* ]

jobs:
  verify-feature-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Cache owasp-dependency-check files
      id: maven-cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-owasp-

    - name: Set up JDK 1.8
      id: checkout
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: zulu
        java-version: 8.0.312+7

    - name: Install Commitlint Dependencies
      id: dependencies
      run: npm install @commitlint/config-conventional

    - name: Lint commit messages
      id: commitlint
      uses: wagoid/commitlint-github-action@v4

    - name: maven verify
      id: verify
      run: mvn clean verify org.owasp:dependency-check-maven:aggregate --file src/pom.xml -Dfmt.skip=true -DskipTests=true -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -DfailBuildOnCVSS=7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

