name: "CI/CD gitflow: push feature branch"
on:
  push:
    branches: [ feature/* ]

jobs:
  verify-feature-build:
    name: Build Feature Branch
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache owasp-dependency-check files
      id: maven-cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-owasp-

    - name: Set up JDK 1.8
      id: checkout
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: zulu
        java-version: 8.0.312+7
        
    - name: Set up nexus
      uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: >
          [
            {
                "id": "dev-nexus-abvprp",
                "username": "${{ secrets.nexus_username }}",
                "password": "${{ secrets.nexus_password }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "dev-nexus-abvprp",
              "name": "Above Property Nexus",
              "mirrorOf": "external:*",
              "url": "https://nexus.dev.abvprp.com/repository/Public-Repositories/"
            }
          ]
        
    - run: cat $HOME/.m2/settings.xml
    
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: >
          [
            {
              "id": "some-repository",
              "name": "some-repository-name",
              "url": "http://some.repository.url",
              "releases": {
                "enabled": "true",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              },
              "snapshots": {
                "enabled": "false",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "some-plugin-repository",
              "name": "some-plugin-repository-name",
              "url": "http://some.plugin.repository.url",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "false"
              }
            }
          ]
        servers: >
          [
            {
              "id": "some-id",
              "username": "${env.USER}",
              "password": "${env.PASS}",
              "configuration": {
                "httpConfiguration": {
                  "all": {
                    "usePreemptive": "true"
                  }
                }
              }
            }
          ]
        mirrors: >
          [
            {
              "id": "nexus",
              "mirrorOf": "!my-org-snapshots,*",
              "url": "http://redacted/nexus/content/groups/public"
            }
          ]
        profiles: >
          [
            {
              "id": "foo.profile",
              "name": "foo.profile",
              "url": "http://foo.bar.profile",
              "properties": {
                "foo": "property-1",
                "bar": "property-2"
              }
            }
          ]
        plugin_groups: >
          [
            "some.plugin.group.id",
            "some.other.plugin.group.id"
          ]
        proxies: >
          [
            {
              "id": "foo-proxy",
              "active": "true",
              "protocol": "http",
              "host": "https://proxy.example.com",
              "port": "443",
              "username": "foo",
              "password": "bar",
              "nonProxyHosts": "noproxy1.example.com|noproxy2.example.com"
            }
          ]
        active_profiles: >
          [
            "some-profile"
          ]
    - run: cat m2_settings.xml

    - name: Install Commitlint Dependencies
      id: dependencies
      run: npm install @commitlint/config-conventional

    - name: Lint commit messages
      id: commitlint
      uses: wagoid/commitlint-github-action@v4
      with:
        configFile: .commitlint.config.js

    - name: maven verify
      id: verify
      run: mvn clean verify org.owasp:dependency-check-maven:aggregate --file pom.xml -Dfmt.skip=true -DskipTests=true -fae -B -DfailBuildOnCVSS=7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

