name: pr-name-linter
on:
  push:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: npm install @commitlint/config-conventional

    - uses: JulienKode/pull-request-name-linter-action@v0.4.0

    - uses: wagoid/commitlint-github-action@v4
